name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y bc build-essential wget git autoconf libncurses-dev bison flex libssl-dev libelf-dev
    
    - name: Run build-all.sh
      run: ./build-all.sh
